In [1]:
import pandas as pd
from keras.models import Sequential
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from keras.models import load_model

Using TensorFlow backend.

In [2]:
####### Predict Total Earnings for Video Game ############

In [3]:
# Load training data set from CSV file
training_data_df = pd.read_csv('sales_data_training.csv')

In [4]:
training_data_df.head()

,critic_rating,is_action,is_exclusive_to_us,is_portable,is_role_playing,is_sequel,is_sports,suitable_for_kids,total_earnings,unit_price
0,3.5,1,0,1,0,1,0,0,132717,59.99
1,4.5,0,0,0,0,1,1,0,83407,49.99
2,3.0,0,0,0,0,1,1,0,62423,49.99
3,4.5,1,0,0,0,0,0,1,69889,39.99
4,4.0,1,0,1,0,1,0,1,161382,59.99

In [5]:
# Load testing data set from CSV file
test_data_df = pd.read_csv('sales_data_test.csv')

In [6]:
test_data_df.head()

,critic_rating,is_action,is_exclusive_to_us,is_portable,is_role_playing,is_sequel,is_sports,suitable_for_kids,total_earnings,unit_price
0,3.5,1,1,1,0,1,0,1,247537,59.99
1,2.5,0,0,0,1,1,0,0,73960,59.99
2,3.5,0,0,0,0,1,1,0,82671,59.99
3,4.0,1,1,0,0,1,0,0,137456,39.99
4,2.0,1,0,1,0,1,0,0,89639,59.99

In [7]:
# Data needs to be scaled to a small range like 0 to 1 for the neural
# network to work well.
scaler = MinMaxScaler(feature_range=(0,1))

In [8]:
# Scale both the training inputs and outputs
scaled_training = scaler.fit_transform(training_data_df)
scaled_testing = scaler.fit_transform(test_data_df)

In [9]:

# Print out the adjustment that the scaler applied to the total_earnings column of data
print("Note: total_earnings values were scaled by multiplying by {:.10f} and adding {:.6f}".format(scaler.scale_[8], scaler.min_[8]))

Note: total_earnings values were scaled by multiplying by 0.0000042367 and adding -0.153415

In [10]:
# Create new pandas DataFrame objects from the scaled data
scaled_training_df = pd.DataFrame(scaled_training, columns=training_data_df.columns.values)
scaled_testing_df = pd.DataFrame(scaled_testing, columns=test_data_df.columns.values)

In [11]:
# Save scaled data dataframes to new CSV files
scaled_training_df.to_csv("sales_data_training_scaled.csv", index=False)
scaled_testing_df.to_csv("sales_data_test_scaled.csv", index=False)

In [12]:
training_data_df_scaled = pd.read_csv("sales_data_training_scaled.csv")
training_data_df_scaled.head()

,critic_rating,is_action,is_exclusive_to_us,is_portable,is_role_playing,is_sequel,is_sports,suitable_for_kids,total_earnings,unit_price
0,0.500000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.374714,1.0
1,0.833333,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.192425,0.5
2,0.333333,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.114852,0.5
3,0.833333,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.142452,0.0
4,0.666667,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.480682,1.0

In [13]:
X = training_data_df_scaled.drop('total_earnings', axis=1).values
Y = training_data_df_scaled[['total_earnings']].values

# Define the model
model = Sequential()
model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(
    X,
    Y,
    epochs=50,
    shuffle=True,
    verbose=2
)

Epoch 1/50
 - 1s - loss: 0.0346
Epoch 2/50
 - 0s - loss: 0.0048
Epoch 3/50
 - 0s - loss: 0.0018
Epoch 4/50
 - 0s - loss: 8.5914e-04
Epoch 5/50
 - 0s - loss: 4.5658e-04
Epoch 6/50
 - 0s - loss: 2.6425e-04
Epoch 7/50
 - 0s - loss: 1.9665e-04
Epoch 8/50
 - 0s - loss: 1.3480e-04
Epoch 9/50
 - 0s - loss: 1.0088e-04
Epoch 10/50
 - 0s - loss: 8.4523e-05
Epoch 11/50
 - 0s - loss: 6.8362e-05
Epoch 12/50
 - 0s - loss: 5.8142e-05
Epoch 13/50
 - 0s - loss: 5.1911e-05
Epoch 14/50
 - 0s - loss: 4.4638e-05
Epoch 15/50
 - 0s - loss: 5.0661e-05
Epoch 16/50
 - 0s - loss: 4.6242e-05
Epoch 17/50
 - 0s - loss: 4.1332e-05
Epoch 18/50
 - 0s - loss: 3.3192e-05
Epoch 19/50
 - 0s - loss: 3.1578e-05
Epoch 20/50
 - 0s - loss: 3.2839e-05
Epoch 21/50
 - 0s - loss: 3.9240e-05
Epoch 22/50
 - 0s - loss: 3.5365e-05
Epoch 23/50
 - 0s - loss: 2.7566e-05
Epoch 24/50
 - 0s - loss: 2.7898e-05
Epoch 25/50
 - 0s - loss: 3.5049e-05
Epoch 26/50
 - 0s - loss: 2.9765e-05
Epoch 27/50
 - 0s - loss: 3.0547e-05
Epoch 28/50
 - 0s - loss: 2.9642e-05
Epoch 29/50
 - 0s - loss: 2.8063e-05
Epoch 30/50
 - 0s - loss: 3.0192e-05
Epoch 31/50
 - 0s - loss: 3.1313e-05
Epoch 32/50
 - 0s - loss: 2.3450e-05
Epoch 33/50
 - 0s - loss: 2.4480e-05
Epoch 34/50
 - 0s - loss: 2.4857e-05
Epoch 35/50
 - 0s - loss: 2.7262e-05
Epoch 36/50
 - 0s - loss: 2.9101e-05
Epoch 37/50
 - 0s - loss: 3.4205e-05
Epoch 38/50
 - 0s - loss: 2.8926e-05
Epoch 39/50
 - 0s - loss: 3.1511e-05
Epoch 40/50
 - 0s - loss: 3.6131e-05
Epoch 41/50
 - 0s - loss: 2.5328e-05
Epoch 42/50
 - 0s - loss: 2.5681e-05
Epoch 43/50
 - 0s - loss: 3.1563e-05
Epoch 44/50
 - 0s - loss: 2.4061e-05
Epoch 45/50
 - 0s - loss: 2.1202e-05
Epoch 46/50
 - 0s - loss: 2.0428e-05
Epoch 47/50
 - 0s - loss: 2.4419e-05
Epoch 48/50
 - 0s - loss: 2.2015e-05
Epoch 49/50
 - 0s - loss: 2.7095e-05
Epoch 50/50
 - 0s - loss: 1.8517e-05

In [14]:
# Load the separate test data set
test_data_df_scaled = pd.read_csv("sales_data_test_scaled.csv")

X_test = test_data_df_scaled.drop('total_earnings', axis=1).values
Y_test = test_data_df_scaled[['total_earnings']].values

test_error_rate = model.evaluate(X_test,Y_test,verbose=0)
print("The mean squared error (MSE) for the test data set is: {}".format(test_error_rate))

The mean squared error (MSE) for the test data set is: 0.0013924493780359626

In [15]:
pedicted_data= model.predict(X_test)

In [16]:
pedicted_data

array([[ 0.80301076],
       [ 0.16264383],
       [ 0.19209723],
       [ 0.39437357],
       [ 0.22807366],
       [ 0.26526263],
       [ 0.23011546],
       [ 0.7164314 ],
       [ 0.42836294],
       [ 0.39410245],
       [ 0.23225933],
       [ 0.3343694 ],
       [ 0.25039557],
       [ 0.3447453 ],
       [ 0.4098072 ],
       [ 0.2206171 ],
       [ 0.28036073],
       [ 0.04970721],
       [ 0.23225933],
       [ 0.27120352],
       [ 0.19852903],
       [ 0.2788736 ],
       [ 0.39410245],
       [ 0.20691583],
       [ 0.4159467 ],
       [ 0.28036073],
       [ 0.40832534],
       [ 0.18019092],
       [ 0.14552687],
       [ 0.2792821 ],
       [ 0.16264378],
       [ 0.57729274],
       [ 0.18613572],
       [ 0.6026077 ],
       [ 0.19371545],
       [ 0.1301994 ],
       [ 0.34451425],
       [ 0.1656725 ],
       [ 0.45761004],
       [ 0.7310489 ],
       [ 0.05565917],
       [ 0.11834043],
       [ 0.2751626 ],
       [ 0.08543984],
       [ 0.22861218],
       [ 0.17680278],
       [ 0.05105326],
       [ 0.8101441 ],
       [ 0.18019092],
       [ 0.254637  ],
       [ 0.08067071],
       [ 0.73035496],
       [ 0.20285538],
       [ 0.18613572],
       [ 0.12280607],
       [ 0.33436942],
       [ 0.36115286],
       [ 0.1430434 ],
       [ 0.6236002 ],
       [ 0.7326525 ],
       [ 0.15240052],
       [ 0.89126325],
       [ 0.309805  ],
       [ 0.10938226],
       [ 0.18479118],
       [ 0.3810918 ],
       [ 0.58108544],
       [ 0.3343694 ],
       [ 0.35484388],
       [ 0.3447453 ],
       [ 0.2595592 ],
       [ 0.26635733],
       [ 0.6545736 ],
       [ 0.11220012],
       [ 0.15696567],
       [ 0.43974498],
       [ 0.9015384 ],
       [ 0.3102908 ],
       [ 0.08566903],
       [ 0.4220318 ],
       [ 0.3239424 ],
       [ 0.1688065 ],
       [ 0.3239424 ],
       [ 0.21165511],
       [ 0.71643144],
       [ 0.21485607],
       [ 0.2028554 ],
       [ 0.09957696],
       [ 0.43387526],
       [ 0.16264383],
       [ 0.21057257],
       [ 0.09270729],
       [ 0.23225933],
       [ 0.22456153],
       [ 0.4309642 ],
       [ 0.1537852 ],
       [ 0.36211357],
       [ 0.37489983],
       [ 0.1430377 ],
       [ 0.09464251],
       [ 0.2069158 ],
       [ 0.3481387 ],
       [ 0.34559056],
       [ 0.2028554 ],
       [ 0.23011547],
       [ 0.2595592 ],
       [ 0.32103738],
       [ 0.3343694 ],
       [ 0.22123486],
       [ 0.11443453],
       [ 0.42455938],
       [ 0.2466571 ],
       [ 0.09957695],
       [ 0.29229504],
       [ 0.02971486],
       [ 0.8052165 ],
       [ 0.43635264],
       [ 0.21809456],
       [ 0.3481387 ],
       [ 0.37579814],
       [ 0.17390162],
       [ 0.37489983],
       [ 0.4415473 ],
       [ 0.23572531],
       [ 0.30980507],
       [ 0.19209723],
       [ 0.16397257],
       [ 0.44076863],
       [ 0.3239424 ],
       [ 0.1301994 ],
       [ 0.37859988],
       [ 0.54163295],
       [ 0.1592859 ],
       [ 0.30980507],
       [ 0.61126876],
       [ 0.2206171 ],
       [ 0.433069  ],
       [ 0.254637  ],
       [ 0.22061709],
       [ 0.17694019],
       [ 0.23435795],
       [ 0.39437357],
       [ 0.05504809],
       [ 0.53319204],
       [ 0.4262957 ],
       [ 0.18613572],
       [ 0.25120685],
       [ 0.26464072],
       [ 0.4159467 ],
       [ 0.23435795],
       [ 0.08279736],
       [ 0.39437363],
       [ 0.20285538],
       [ 0.44773456],
       [ 0.07037795],
       [ 0.3343694 ],
       [ 0.4262957 ],
       [ 0.44883257],
       [ 0.21057254],
       [ 0.22807363],
       [ 0.23435795],
       [ 0.19209723],
       [ 0.12663378],
       [ 0.433069  ],
       [ 0.18204519],
       [ 0.37859988],
       [ 0.24258113],
       [ 0.42629567],
       [ 0.65306   ],
       [ 0.09957695],
       [ 0.42836294],
       [ 0.20309013],
       [ 0.7326525 ],
       [ 0.39861882],
       [ 0.37859985],
       [ 0.09135634],
       [ 0.40760908],
       [ 0.2818523 ],
       [ 0.27230835],
       [ 0.21057257],
       [ 0.24770689],
       [ 0.16556211],
       [ 0.37859985],
       [ 0.11579404],
       [ 0.10564254],
       [ 0.3187019 ],
       [ 0.32947364],
       [ 0.3102908 ],
       [ 0.25256827],
       [ 0.18676078],
       [ 0.26977164],
       [ 0.14552686],
       [ 0.53319204],
       [ 0.09388834],
       [ 0.20577724],
       [ 0.3481387 ],
       [ 0.11600217],
       [ 0.04129399],
       [ 0.13418889],
       [ 0.2206171 ],
       [ 0.4708963 ],
       [ 0.30605963],
       [ 0.45879838],
       [ 0.29229504],
       [ 0.21809456],
       [ 0.11220012],
       [-0.03611105],
       [ 0.15696564],
       [ 0.3449463 ],
       [ 0.6026077 ],
       [ 0.40760908],
       [ 0.2891685 ],
       [ 0.22061709],
       [ 0.8100534 ],
       [ 0.18279818],
       [ 0.4220318 ],
       [ 0.084201  ],
       [ 0.22061709],
       [ 0.22061709],
       [ 0.12290719],
       [ 0.09159931],
       [ 0.11834043],
       [ 0.29229504],
       [ 0.11692509],
       [ 0.53869367],
       [ 0.27230835],
       [ 0.58108544],
       [ 0.19166133],
       [ 0.2339766 ],
       [ 0.37084112],
       [ 0.23225936],
       [ 0.08861177],
       [ 0.4708963 ],
       [ 0.30980507],
       [ 0.6598268 ],
       [ 0.15531304],
       [ 0.504852  ],
       [ 0.5027282 ],
       [ 0.13418889],
       [ 0.7326525 ],
       [ 0.37579814],
       [ 0.37489983],
       [ 0.5542088 ],
       [ 0.4415473 ],
       [ 0.3343694 ],
       [ 0.11009128],
       [ 0.2028554 ],
       [ 0.24770692],
       [ 0.5853448 ],
       [ 0.23230009],
       [ 0.1430434 ],
       [ 0.18569438],
       [ 0.47598466],
       [ 0.34871224],
       [ 0.18983145],
       [ 0.06786629],
       [ 0.20391804],
       [ 0.29367682],
       [ 0.32583666],
       [ 0.26714218],
       [ 0.5772926 ],
       [ 0.18569438],
       [ 0.20397031],
       [ 0.51366097],
       [ 0.24536298],
       [ 0.6537344 ],
       [ 0.14825325],
       [ 0.33235416],
       [ 0.23435795],
       [ 0.24770689],
       [ 0.2245615 ],
       [ 0.30980507],
       [ 0.8052165 ],
       [ 0.14074107],
       [ 0.17694019],
       [ 0.09353571],
       [ 0.42455938],
       [ 0.26635733],
       [ 0.20691583],
       [ 0.6026077 ],
       [ 0.04970721],
       [ 0.210495  ],
       [ 0.5926697 ],
       [ 0.3011988 ],
       [ 0.80301076],
       [ 0.38071468],
       [ 0.27230835],
       [ 0.08779382],
       [ 0.2751626 ],
       [ 0.5772926 ],
       [ 0.43669972],
       [ 0.37579814],
       [ 0.19071911],
       [ 0.24754399],
       [ 0.47577032],
       [ 0.15194888],
       [ 0.24040747],
       [ 0.47577032],
       [ 0.162117  ],
       [ 0.24891566],
       [ 0.2098234 ],
       [ 0.4159467 ],
       [ 0.2926021 ],
       [ 0.29229504],
       [ 0.23572531],
       [ 0.16556211],
       [ 0.65306   ],
       [ 0.36314508],
       [ 0.12663378],
       [ 0.29229504],
       [ 0.3454831 ],
       [ 0.18204519],
       [ 0.71643144],
       [ 0.27230835],
       [ 0.39584953],
       [ 0.3102908 ],
       [ 0.5250036 ],
       [ 0.4262957 ],
       [ 0.15153632],
       [ 0.2339766 ],
       [ 0.15531304],
       [ 0.74347097],
       [ 0.29694736],
       [ 0.27230835],
       [ 0.8100534 ],
       [ 0.22061709],
       [ 0.58534485],
       [ 0.2891685 ],
       [ 0.30605963],
       [ 0.2069158 ],
       [ 0.4262957 ],
       [ 0.1567664 ],
       [ 0.3315374 ],
       [ 0.22807366],
       [ 0.04388767],
       [ 0.26635733],
       [ 0.13438128],
       [ 0.43635264],
       [ 0.5713796 ],
       [ 0.39609012],
       [ 0.1934149 ],
       [ 0.24754399],
       [ 0.2969473 ],
       [ 0.29229504],
       [ 0.57522285],
       [ 0.6545736 ],
       [ 0.42606255],
       [ 0.1384733 ],
       [ 0.4094435 ],
       [ 0.29229504],
       [ 0.23421544],
       [ 0.01439817],
       [ 0.09541932],
       [ 0.07037795],
       [ 0.3396612 ],
       [ 0.40760908],
       [ 0.08929306],
       [ 0.6545736 ],
       [ 0.2343579 ],
       [ 0.25213525],
       [ 0.29229504],
       [ 0.37579814],
       [ 0.65306   ],
       [ 0.1178011 ],
       [ 0.43635264],
       [ 0.21057257],
       [ 0.28736123],
       [ 0.4342917 ],
       [ 0.28115532],
       [ 0.16397259],
       [ 0.2339766 ],
       [ 0.15240052],
       [ 0.29947403],
       [ 0.1407269 ],
       [ 0.17963913],
       [ 0.47577032],
       [ 0.20051455],
       [ 0.06222338],
       [ 0.27230835],
       [ 0.23435795],
       [ 0.33235416],
       [ 0.1592859 ],
       [ 0.16617659],
       [ 0.09327265],
       [ 0.50711733],
       [ 0.39584953],
       [ 0.19852903],
       [ 0.05565917],
       [ 0.23011547],
       [ 0.16397259],
       [ 0.1592859 ],
       [ 0.17498499],
       [ 0.1082166 ],
       [ 0.2366484 ],
       [ 0.12141856],
       [ 0.23572531],
       [ 0.3343694 ],
       [ 0.4162092 ],
       [ 0.10639698],
       [ 0.1711064 ]], dtype=float32)

In [17]:
test_data_df_scaled.head()

,critic_rating,is_action,is_exclusive_to_us,is_portable,is_role_playing,is_sequel,is_sports,suitable_for_kids,total_earnings,unit_price
0,0.500000,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.895324,1.0
1,0.166667,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.159931,1.0
2,0.500000,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.196837,1.0
3,0.666667,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.428944,0.0
4,0.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.226358,1.0

In [18]:
# Save the model to disk
model.save("trained_mode.h5")
print("Model Saved to Disk")

Model Saved to Disk

In [19]:
# Load the data we make to use to make a prediction
X = pd.read_csv("proposed_new_product.csv").values

#Load model from trained data
model = load_model('trained_mode.h5')

# Make a prediction with the neural network
prediction = model.predict(X)

# Grab just the first element of the first prediction (since that's the only have one)
prediction = prediction[0][0]

# Re-scale the data from the 0-to-1 range back to dollars
# These constants are from when the data was originally scaled down to the 0-to-1 range
prediction = prediction + 0.1159
prediction = prediction / 0.0000036968

print("Earnings Prediction for Proposed Product - ${}".format(prediction))

Earnings Prediction for Proposed Product - $264618.1214761228

In [20]:
X

array([[0.7, 1. , 1. , 1. , 0. , 1. , 0. , 1. , 0.8]])